spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chuvak?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: chuvak
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

cross_origin : http://localhost:8080
springdoc : 
  swagger-ui : 
    path : /swagger-ui